#!/usr/bin/env perl
use v5.40;

use strict;
use warnings;
use utf8;
use utf8::all;

# Main Testbench
use Data::Dumper;
use Moose;
use Acuarela::Color::RGBA;
use diagnostics;

my $test_color = Acuarela::Color::RGBA->new(
    "channels"  => {'r' => 0, 'g' => 200, 'b' => 200, 'a' => 255}
);

my @test_spaces = qw("BRAILLE" "CMY" "CMYK" "HEX" "HSL" "HSV");

print("Test Color [OBJECT]\t=\t$test_color\n");

foreach(@test_spaces) {
    my $test_str = $test_color->convert_to($_);
    print("Test color conversion: $test_str\n");
}

#print(Term::ANSIColor::color)
